# Generated by Django 4.2.2 on 2023-06-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN_id', models.IntegerField(max_length=50)),
                ('ADMIN_Usname', models.TextField(max_length=50)),
                ('ADMIN_Lastname', models.TextField(max_length=50)),
                ('ADMIN_age', models.TextField(max_length=50)),
                ('ADMIN_password', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=50)),
                ('category_description', models.TextField(max_length=50)),
                ('category_image', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('Customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('email', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=20)),
                ('Address', models.TextField(max_length=200)),
                ('City', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('postal_Code', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.TextField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_date', models.TextField(max_length=50)),
                ('total_amount', models.TextField(max_length=50)),
                ('payment_type', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.TextField(max_length=200)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_name', models.TextField(max_length=50)),
                ('quantity', models.TextField(max_length=50)),
                ('item_notes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_discount', models.TextField(max_length=50)),
                ('item_total', models.TextField(max_length=50)),
                ('item_status', models.TextField(max_length=50)),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.orders')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.products')),
            ],
        ),
    ]
