# Generated by Django 4.2.2 on 2023-06-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='ADMIN_Lastname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='ADMIN_Usname',
            new_name='Usname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='ADMIN_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='ADMIN_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='ADMIN_id',
        ),
    ]
