# Generated by Django 4.2.2 on 2023-06-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='meaning',
            new_name='age',
        ),
    ]
