# Generated by Django 4.2.2 on 2023-06-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_remove_customers_customers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='emali',
            new_name='email',
        ),
    ]
