# Generated by Django 4.2.2 on 2023-06-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_rename_emali_customers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
